### PR TITLE
Parallel SageAttention Inference

### PR DESCRIPTION
**Pull request by DefTruth**
This PR add a small workaround that can make sage attention work compatible with distributed env, for example, xDiT which will launch by torchrun. Without this workaround, sage attention will run into illegal memory access error after first inference step in distributed env for multi gpus inference. This small workaround also make sage attention work compatible with torch.compile through non-fullgraph compile mode.

@jason-huang03

### CODE REVIEW

**Comment by jason-huang03** [comment]
Thanks a lot! We well check the implementation and merge the PR.

**Comment by DefTruth** [comment]
make need to install latest xDiT from source if your env already have FA>=2.7.0, i have make hotfix to ensure ring flash attn forward compatible with lastest FA.

**Comment by DefTruth** [comment]
make need to install latest xDiT from source if your env already have FA>=2.7.0, i have make hotfix to ensure ring flash attn forward compatible with lastest FA.

also, the plug-and-play sage attention can only work with CFG parallelism for 2 GPUs now.

**Comment by jason-huang03** [comment]
I am busy these days and I will dive into it as soon as I can.

**Pull request merged**
